batch_size: 64
height: 50
learning_rate: 0.001
max_text_length: 7
model_path: Models/02_captcha_to_text\202403141135
train_epochs: 1000
train_workers: 20
vocab: upq625vk1jtye9lz38c7w0fxsbdinhra4mog
width: 200
